Added and revised interface doc for GenerateImageClassifierBlackboxSa…
XAITK/xaitk-saliency pull request #58
Opened 2021-09-19 21:46 UTC by melster1010

…liency

2021-09-21 15:12 UTC, Purg requested changes

2021-09-21 19:26 UTC, melster1010 commented on docs/api_docs.rst
> +A candidate implementation for this interface is the D-RISE [4] algorithm.
thanks, I was making an educated guess, guessed wrong :)

2021-09-21 19:31 UTC, brianhhu commented
Not tied to additions in this specific PR, but going through the code/documentation for our [two utility masking functions](https://github.com/XAITK/xaitk-saliency/blob/master/xaitk_saliency/utils/masking.py#L13-L194) yesterday, I believe the current stated return output is incorrect. It currently states that both utility functions return a list of `PIL` images, but I believe the correct output is either a numpy array of masked images (batch) or a generator of numpy array masked images (streaming).

We could consider fixing the docstrings as part of this PR.

https://github.com/XAITK/xaitk-saliency/blob/master/xaitk_saliency/utils/masking.py#L68
https://github.com/XAITK/xaitk-saliency/blob/master/xaitk_saliency/utils/masking.py#L159

2021-09-21 20:45 UTC, Purg commented
> ... the current stated return output is incorrect. ...

Oops! Good catch.

2021-09-22 12:48 UTC, melster1010 commented
> Not tied to additions in this specific PR, but going through the code/documentation for our [two utility masking functions](https://github.com/XAITK/xaitk-saliency/blob/master/xaitk_saliency/utils/masking.py#L13-L194) yesterday, I believe the current stated return output is incorrect. It currently states that both utility functions return a list of `PIL` images, but I believe the correct output is either a numpy array of masked images (batch) or a generator of numpy array masked images (streaming).

I changed the docstrings to indicate batch returns "a numpy array of masked images" and streaming returns "a generator of numpy array masked images".

2021-09-22 18:29 UTC, brianhhu commented on docs/api_docs.rst
> +(RISEStack and/or SlidingWindowStack).
Minor nitpick:

```suggestion
(``RISEStack`` and/or ``SlidingWindowStack``).
```

2021-09-22 18:30 UTC, brianhhu commented on docs/api_docs.rst
> +(RISEStack and/or SlidingWindowStack).
Minor nitpick:

```suggestion
A candidate implementation for this interface is the ``PerturbationOcclusion`` implementation or its sub-implementations
(``RISEStack`` and/or ``SlidingWindowStack``).
```

2021-09-23 14:10 UTC, Purg reviewed
Minor issue with bullet formatting.

2021-09-23 14:10 UTC, Purg commented on docs/api_docs.rst
> +optional parallelization in that streaming
The second line of text needs to align with the bullet indentation to be considered part of the same block.
```suggestion
* ``xaitk_saliency.utils.masking.occlude_image_streaming`` - performs the transformation in a streaming method with
  optional parallelization in that streaming
```

2021-09-27 13:10 UTC, brianhhu commented
LGTM, a rebase will be needed. Thanks!

2021-09-27 13:44 UTC, Purg approved these changes
LGTM

2021-09-27 14:18 UTC, merged